### ISSUE TITLE
Running the miner individually

### ISSUE THREAD

**Issue by renderit** [Anthony-Tatowicz/cuda-ethminer#5]
Hey Anthony,
Great work here. I was trying to make this run on a my pretty big nvidia GPU's. I'm sorry I'm a beginner with this. I'm not sure what and how to use stratum. Is it required to use this? Can I run this individually? 
I was trying:
```
$~  nvidia-docker run -it anthonytatowicz/eth-cuda-miner -O 0x311Ac4E60CD56CF19816fEbC4f7E9B77d36dE2b

 I get error: 
JSON-RPC problem. Probably couldn't connect. Retrying in 1...
^C
  m  04:24:41|ethminer  Getting work package...
  ✘  04:24:41|ethminer  Failed to submit hashrate.
  ✘  04:24:41|ethminer  Dynamic exception type: jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 7 -> Could not connect to http://127.0.0.1:8545

```

**Comment by tatowicz** [comment]
Stratum is used to connect to a mining pool, you can set the stratum host with the `-S <host>` argument.
In most cases you will want to use a pool to mine, since it will give you the most profit i.e. the `income -
 cost` where income is the value of eth mined and cost is how much was spent on electricity to mine. If you think you have a considerable hash rate then it may be better to mine independently from a pool, but you will need to determine that on your own. Keep in mind if your hashrate is low it may take many months to acquire a single block leaving you with very unstable income.
I can give you some direction on the calculations though. First I would search for a profitability calculator on the internet to get a good idea what you could make with current eth prices and electricity costs, also calculate the approximate time to win a block with your hashrate in order to get a sense of income stability, this will be approximate since it is a probability. To calculate the approximate time to win a block you would use this logic...

Since there is a 5 eth reward per block and lets assume one block per minute the daily eth output of the network would be

`network eth per day = 60*24*5`

Keep in mind this is probably inaccurate I would use <https://etherscan.io/chart/blocks> to take an average of the blocks per day and use that to calculate eth per day like so

`network eth per day = 5 * average blocks per day`
 
now calculate the probability of winning a block like so,

 `P(win) = your hash rate / network hash rate`

This leads to the approximation of eth per day

`your eth per day = P(win) * network eth per day`

Remember that in order to mine ether you must win a block and which is a 5 eth reward, so to calculate the time to win one block you would do this

`days for block = 5 / your eth per day`

This should put you in the right direction, if you want more evidence I would suggest research more on the internet, but you should find similar advice. If you decide you want to mine independently you will need to mine without stratum, so you will have only the `-U` option, in order for this to work I believe I will need to update the Dockerfile leaving the `--farm-recheck` option out. I will update this soon as I migrate to the more maintained ethminer repository.

**Comment by renderit** [comment]
@Anthony-Tatowicz Excellent. Thanks for that explanations.. I guess It would be great to explore and test both options in the next few days (with and without mining pool). Speaking of joining a stratum pool, how exactly do I join? I went to: `https://eth.nanopool.org/help` and clicked on `Generate your config` button. It gives me a bash file and epools text file. The bash file looks something like:
`./ethdcrminer64 -epool eth-us-west1.nanopool.org:9999 -ewal 0x311ac4e60cd56cf19816febc4f7e9b77d36de2bc.mydg1rig/mudit.dfm@gmail.com -epsw x -mode 1 -ftime 10`

Not sure how to proceed. :(  Thanks in advance.

**Comment by tatowicz** [comment]
Basically with nanopool your address is your account, so what will happen is when starting up a miner pass in arguments for your eth address, the address of the stratum host nearest to you and your email, so in your case the command would look like this

```
nvidia-docker run -it anthonytatowicz/eth-cuda-miner \
-S us-west1.nanopool.org:9999 \
-O 0x311ac4e60cd56cf19816febc4f7e9b77d36de2bc.mydg1rig/mudit.dfm@gmail.com \
--farm-recheck 200
```

be sure to double check your email and eth address and make sure they are correct and check that the images is updated.
